version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/{{cookiecutter.module_name}}"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/{{cookiecutter.module_name}}/tests"
    update_schedule: "daily"

  - package_manager: "python"
    directory: "/"
    update_schedule: "live"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/{{cookiecutter.module_name}}"
    update_schedule: "daily"
